apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{deployment_name}}
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: "{{host_name}}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{deployment_name}}
          servicePort: 80