apiVersion: v1
kind: Service
metadata:
  name: {{deployment_name}}
  namespace: default
  labels:
    component: {{deployment_name}}
spec:
  selector:
    component: {{deployment_name}}
  ports:
  - name: http
    port: 80
    targetPort: http